/*amd /edu01.xml 2920 fbff6a414ab13256751407d0dc5d7cbaea262704d71cd9a177cfaf080d4f034e */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataMap',A:{baseNode:'map',id:'dataMap1'},E:[{T:1,N:'w2:keyInfo',E:[{T:1,N:'w2:key',A:{id:'key1',name:'name1',dataType:'text'}},{T:1,N:'w2:key',A:{id:'key2',name:'name2',dataType:'text'}},{T:1,N:'w2:key',A:{id:'key3',name:'name3',dataType:'text'}}]},{T:1,N:'w2:data',E:[{T:1,N:'key1'},{T:1,N:'key2'},{T:1,N:'key3'}]}]},{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dataList1',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'col1',name:'name1',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col2',name:'name2',dataType:'text'}},{T:1,N:'w2:column',A:{id:'col3',name:'name3',dataType:'text'}}]},{T:1,N:'w2:data',E:[{T:1,N:'w2:row'},{T:1,N:'w2:row'},{T:1,N:'w2:row'}]}]},{T:1,N:'w2:linkedDataList',A:{bind:'',id:'linkedDataList1'},E:[{T:1,N:'w2:condition',A:{type:'filter'}},{T:1,N:'w2:condition',A:{type:'sort'}}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
scwin.onpageload = function() {
	//init 함수 기능
     ipt1.setValue("987654321")


};

scwin.ipt1_onclick = function(e) {

};

}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'xf:input',A:{id:'ipt1',style:'width:201px;height:49px;margin-right: 10px;',initValue:'123456789',dataType:'number',displayFormat:'#,###',applyFormat:'all','ev:onclick':'scwin.ipt1_onclick',ref:'data:dataMap1.key2'}},{T:1,N:'w2:searchbox',A:{id:'',style:'width: 150px;height: 21px;'}},{T:1,N:'xf:secret',A:{id:'',style:'width: 144px;height: 21px;'}},{T:1,N:'w2:inputCalendar',A:{id:'',style:'width: 150px;height: 23px;',calendarValueType:'yearMonthDate'}},{T:1,N:'w2:editor',A:{style:'width: 500px;height: 300px;',id:''}},{T:1,N:'w2:textbox',A:{id:'',label:'1줄<br/>2줄',style:'width:207px;height:70px;',tagname:'h2',escape:'false'}},{T:1,N:'w2:multiupload',A:{mode:'html5_transparent',style:'width: 500px;height: 150px;',id:'',uploadButton:''}},{T:1,N:'xf:group',A:{id:'',style:'width: 200px;height: 200px;'},E:[{T:1,N:'xf:input',A:{id:'',style:'width: 144px;height: 21px;'}}]},{T:1,N:'w2:windowContainer',A:{id:'',style:'position: relative;width: 500px;height: 300px;'},E:[{T:1,N:'w2:windowToolbar',E:[{T:1,N:'w2:controlIconLayer',E:[{T:1,N:'w2:controlIcon'},{T:1,N:'w2:controlIcon'},{T:1,N:'w2:controlIcon'},{T:1,N:'w2:controlIcon'},{T:1,N:'w2:controlIcon'}]},{T:1,N:'w2:nameLayer'},{T:1,N:'w2:selectedNameLayer'}]}]}]}]}]})