/*amd /page/P00412.xml 3267 e1196089230a665aa52d6f20763f665528e79c0c38ecb634bc76bfeead9e0a4d */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',A:{},E:[{T:1,N:'w2:historyInfo',E:[{T:1,N:'w2:history',A:{}}]},{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'}},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
scwin.onpageload = function () {

};

/**
 * 버튼 [타이틀 변경하기] 클릭 시
 */
scwin.btn_exam2_1_onclick = function (e) {
    // FloatingLayer 'flt_exam2'의 타이틀을 변경합니다.
    flt_exam2.setTitle("타이틀이 변경되었습니다");
};


}}}]},{T:1,N:'style',A:{type:'text/css'},E:[{T:4,cdata:'.P00412_closeButton{display:none}'}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'xf:group',A:{class:'sub_contents',id:'',style:''},E:[{T:1,N:'xf:group',A:{class:'ws_example_grp_desc',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{escape:'false',id:'',label:'헤더 영역의 타이틀을 설정하는 예제입니다.<br/>이 기능은 속성 \'title\'과 함수 \'setTitle\'로 구현할 수 있습니다.',style:''}},{T:1,N:'w2:textbox',A:{class:'ws_example_txt_desc_info',escape:'false',id:'',label:'이 예제는 닫기 버튼이 CSS로 감춰진 상태입니다.',style:''}}]},{T:1,N:'xf:group',A:{class:'example_div_tb_style_wrap',id:''},E:[{T:1,N:'xf:group',A:{class:'example_div_tr_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'example_div_th_style',escape:'false',id:'',label:'(기본 설정) 헤더 영역에 타이틀이 설정되지 않은 상태',style:''}},{T:1,N:'xf:group',A:{class:'example_div_td_style',id:'',style:''},E:[{T:1,N:'xf:group',A:{id:'grp_exam1',style:'height: 140px;position: relative;'},E:[{T:1,N:'w2:floatingLayer',A:{fixed:'true',id:'flt_exam1',style:'position:absolute;width:240px;height:140px;',closeButtonClass:'P00412_closeButton'},E:[{T:1,N:'w2:textbox',A:{id:'',label:'콘텐츠 영역입니다.',style:'padding: 12px 6px;'}}]}]}]}]},{T:1,N:'xf:group',A:{class:'example_div_tr_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'example_div_th_style',escape:'false',id:'',label:'헤더 영역에 타이틀이 설정된 상태',style:''}},{T:1,N:'xf:group',A:{class:'example_div_td_style',id:'',style:''},E:[{T:1,N:'xf:group',A:{class:'mb_def_box nobottom',id:'',style:''},E:[{T:1,N:'xf:trigger',A:{class:'btn_exam_exec btn_txt_of',escape:'false','ev:onclick':'scwin.btn_exam2_1_onclick',id:'btn_exam2_1',style:'',type:'button'},E:[{T:1,N:'xf:label',E:[{T:4,cdata:'타이틀 변경하기'}]}]}]},{T:1,N:'xf:group',A:{id:'grp_exam2',style:'height: 140px;position: relative;'},E:[{T:1,N:'w2:floatingLayer',A:{fixed:'true',id:'flt_exam2',style:'position:absolute;width:240px;height:140px;',title:'타이틀 지정 예시입니다',closeButtonClass:'P00412_closeButton'},E:[{T:1,N:'w2:textbox',A:{id:'',label:'콘텐츠 영역입니다.',style:'padding: 12px 6px;'}}]}]}]}]}]}]}]}]}]})