/*amd /page/P00405.xml 4065 d589d3976170c1c890433ad994817ddf9ee1979b69e00c5328fc803e2f12c263 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',A:{},E:[{T:1,N:'w2:historyInfo',E:[{T:1,N:'w2:history',A:{}}]},{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dlt_exam_code',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{id:'label',name:'label',dataType:'text'}},{T:1,N:'w2:column',A:{id:'code',name:'code',dataType:'text'}}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
scwin.onpageload = function () {
    //DataList dlt_exam_code에 데이터 할당
    dlt_exam_code.setJSON([
        { "label": "Apple", "code": "01" },
        { "label": "Pear", "code": "02" },
        { "label": "Grapes", "code": "03" },
        { "label": "Watermelon", "code": "04" },
        { "label": "Peach", "code": "05" }
    ]);

    // 초기 선택 값 할당하기
    ccb_exam1.setValue("02 05");
    ccb_exam2.setValue("02 05");
};

}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'xf:group',A:{class:'sub_contents',id:'',style:''},E:[{T:1,N:'xf:group',A:{class:'ws_example_grp_desc',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{escape:'false',id:'',label:'속성 \'showCheckedTop\'의 설정 값에 따른 비교 예제입니다.<br/>이 속성은 선택 된 항목을 목록 상단에 표시하는 기능을 제공합니다.',style:''}},{T:1,N:'w2:textbox',A:{escape:'false',id:'',label:'이 기능은 속성 \'checkboxClickSync\'의 설정 값이 \'true\'일 때 동작합니다.',style:''}},{T:1,N:'w2:textbox',A:{escape:'false',id:'',label:'설정 값에 따른 동작은 아래와 같습니다.<br/>- "false" : [default] 목록의 순서대로 선택된 항목이 표시됩니다.<br/>- "true" : 선택된 항목이 목록 상단에 표시됩니다.',style:''}},{T:1,N:'w2:textbox',A:{class:'exam_txt req_version',escape:'false',id:'',label:'속성 \'showCheckedTop\'은 아래의 엔진부터 제공됩니다.<br/>- RC: 5.0_5.4786B.20230106.154957<br/>- GA: 5.0_5.4877A.20230405.131227',style:''}}]},{T:1,N:'xf:group',A:{class:'example_div_tb_style_wrap',id:''},E:[{T:1,N:'xf:group',A:{class:'example_div_tr_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'example_div_th_style',escape:'false',id:'',label:'(기본 설정) 목록의 순서에 따라 선택된 항목을 표시하기',style:''}},{T:1,N:'xf:group',A:{class:'example_div_td_style',id:'',style:''},E:[{T:1,N:'xf:checkcombobox',A:{id:'ccb_exam1',displayAllOptionLabel:'false',chooseOption:'',displayMode:'label',style:'width: 150px;min-height:24px;',submenuSize:'auto',allOption:'',disabled:'false',direction:'auto',appearance:'minimal',ref:'',showCheckedTop:'false',checkboxClickSync:'true'},E:[{T:1,N:'xf:choices',E:[{T:1,N:'xf:itemset',A:{nodeset:'data:dlt_exam_code'},E:[{T:1,N:'xf:label',A:{ref:'label'}},{T:1,N:'xf:value',A:{ref:'code'}}]}]}]}]}]},{T:1,N:'xf:group',A:{class:'example_div_tr_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'example_div_th_style',escape:'false',id:'',label:'목록 상단에 선택된 항목을 표시하기',style:''}},{T:1,N:'xf:group',A:{class:'example_div_td_style',id:'',style:''},E:[{T:1,N:'xf:checkcombobox',A:{allOption:'',appearance:'minimal',chooseOption:'',direction:'auto',disabled:'false',displayAllOptionLabel:'false',displayMode:'label',id:'ccb_exam2',ref:'',showCheckedTop:'true',style:'width: 150px;min-height:24px;',submenuSize:'auto',checkboxClickSync:'true'},E:[{T:1,N:'xf:choices',E:[{T:1,N:'xf:itemset',A:{nodeset:'data:dlt_exam_code'},E:[{T:1,N:'xf:label',A:{ref:'label'}},{T:1,N:'xf:value',A:{ref:'code'}}]}]}]}]}]}]}]}]}]}]})